### ISSUE TITLE
OneOrBoth = These?

### ISSUE THREAD

**Issue by jamesdbrock** [jisantuc/purescript-stac#7]
https://github.com/jisantuc/purescript-stac/blob/3abf4c5a41c213adba732fcff327badd51d1f4e1/src/Model/Extent.purs#L13-L16

Maybe this is the type you're looking for? https://pursuit.purescript.org/packages/purescript-these/4.0.0/docs/Data.These

**Comment by jamesdbrock** [comment]
Maybe not, because the items in `These` can be different types. So, not really the same as a list of length 1 or 2.

**Comment by jisantuc** [comment]
Maybe, I mean I could type alias it to `These a a` pretty easily. I think the newtype is probably better than a custom predicate, thanks for the suggestion!

**Comment by jisantuc** [comment]
Yeah that's really quite pleasant, and I think does a better job of passing the validated data through (i.e., post-refinement, it's still a list of maybes, while in this case I get to drop the maybes entirely 😎).
